from . import scm_part
from . import scm_bom
from . import scm_supplier_info
from . import scm_purchase
from . import scm_production
from . import scm_warehouse
from . import scm_stock_move
from . import scm_delivery
from . import scm_incoming_inspection
